#pragma once
#include"TileComponent.h"
#include"TransformComponent.h"
#include"SpriteComponent.h"
#include"KeyboardComponent.h"
#include"LightComponent.h"
#include"InventoryComponent.h"
#include"MonsterAIComponent.h"
#include"StatsComponent.h"
#include"CombatComponent.h"
#include"PlayerComponent.h"
#include"SaveInFileComponent.h"
#include"TreasureComponent.h"